### ISSUE TITLE
Kanban Board Review

### ISSUE THREAD

**Issue by topeogunleye** [topeogunleye/recipe-app#21]
### Note to Reviewer: 
There are two people on this team
Github project link: https://github.com/topeogunleye/recipe-app/projects/2

**Comment by TedLivist** [comment]
## STATUS: CHANGES REQUIRED ♻️ ♻️

Hi @topeogunleye,

Good job so far!
✔️ Correct number of cards
However, there are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
**NOTE: Do not create a new issue. Kindly re-submit this same issue after your changes have been made so that the line of communication be easily followed**
- [ ] Your link in the issue directs to the repo (which is close enough), but it should lead to the project itself, which I think is this [link](https://github.com/topeogunleye/recipe-app/projects/2) Kindly correct this.
- [ ] Add the second collaborator to your repo so that you can assign the tasks. Choose who would be Student A and Student B. Take a look at the second image. Kindly ensure that all your cards are assigned accordingly to respective students as highlighted in the first image

  ![emilia-card](https://user-images.githubusercontent.com/36542986/146774280-25b1d048-ae4e-4489-9243-8e963fd56b4f.jpg)

  ![topeogun](https://user-images.githubusercontent.com/36542986/146774307-51be34a5-488a-4e31-a7b9-c6bd4d877552.jpg)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in this thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Lameck1** [comment]
Hi, @topeogunleye & @Gbengacode,

You've done well implementing your Kanban board 👏🏼. 

### Highlights:
- You've properly assigned yourselves tasks ✔️
- Task distribution is fair. The sums of points from your tasks are equal ✔️

You are now set to start working on your project. All the best.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
